php-dev-mysql:
  image: mariadb:latest
  container_name: php-dev-mysql
  volumes:
    - ./var/mysql:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password


php-dev-webserver:
  image: nginx:latest
  container_name: php-dev-webserver
  volumes:
      - ./code:/var/www/php-dev
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx:/var/log/nginx
  ports:
   - "80:80"
  links:
   - php-dev-php-fpm

php-dev-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: php-dev-php-fpm
  volumes:
    - ./code:/var/www/php-dev
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - php-dev-mysql:mysql

php-my-admin:
  image: phpmyadmin/phpmyadmin
  links:
    - php-dev-mysql:mysql
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: password
    PMA_HOST: mysql
  ports:
    - "8080:80"
